"""add video recommendation metadata

Revision ID: 6e541722c2e2
Revises: caf3686b13ff
Create Date: 2026-10-08 20:29:19.765083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e541722c2e2'
down_revision: Union[str, None] = 'caf3686b13ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('engagement_score', sa.Float(), nullable=False))
    op.add_column('recommendations', sa.Column('language_priority_score', sa.Float(), nullable=False))
    op.add_column('recommendations', sa.Column('regional_priority_score', sa.Float(), nullable=False))
    op.add_column('recommendations', sa.Column('thumbnail_language_score', sa.Float(), nullable=False))
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.add_column('videos', sa.Column('thumbnail', sa.String(length=1000), nullable=True))
    op.add_column('videos', sa.Column('language', sa.String(length=10), nullable=False))
    op.add_column('videos', sa.Column('channel_country', sa.String(length=10), nullable=True))
    op.add_column('videos', sa.Column('views', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('thumbnail_has_bengali', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_videos_difficulty_level'), 'videos', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_videos_language'), 'videos', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_language'), table_name='videos')
    op.drop_index(op.f('ix_videos_difficulty_level'), table_name='videos')
    op.drop_column('videos', 'thumbnail_has_bengali')
    op.drop_column('videos', 'likes')
    op.drop_column('videos', 'views')
    op.drop_column('videos', 'channel_country')
    op.drop_column('videos', 'language')
    op.drop_column('videos', 'thumbnail')
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'local'::character varying"),
               existing_nullable=False)
    op.drop_column('recommendations', 'thumbnail_language_score')
    op.drop_column('recommendations', 'regional_priority_score')
    op.drop_column('recommendations', 'language_priority_score')
    op.drop_column('recommendations', 'engagement_score')
    # ### end Alembic commands ###
